version: '3.8'

services:
  server:
    build: .
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db 

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bms_db 
    ports:
      - "3306:3306" 
    volumes:
      - db-data:/var/lib/mysql 

volumes:
  db-data:
