on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL: jdbc:mysql://db:3306/bms_db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: bms_db

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
          MYSQL_DATABASE: ${DB_NAME}
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost --silent" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Wait for Mysql to be ready
        run: |
          until mysqladmin ping -h localhost -p 3306 --silent; do
            echo "Waiting for Mysql to be ready..."
            sleep 2
          done

      - name: Create custom user and database
        run: |
          mysql -h localhost -u root -p'root' -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
          mysql -h localhost -u root -p'root' -e "CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';"
          mysql -h localhost -u root -p'root' -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'root'@'%';"
          mysql -h localhost -u root -p'root' -e "FLUSH PRIVILEGES;"
      

      - name: Build with Maven
        run: mvn clean package